[scrolling]
history = 0

[font]
# normal = { family = "VictorMono Nerd Font" }
normal = { family = "Hack Nerd Font" }
size = 10

[window]
# decorations = "None"
padding = { x = 5, y = 5 }
dynamic_padding = true
opacity = 1.0
